#ESPECIFICACION O VERSION DE DOCKER-COMPOSE
version: "3.9"
#LOS SERVICES SON LOS CONTENEDORES
services:
  mysql-usuarios:
    container_name: mysql-usuarios
    image: mysql:8
    ports:
      - "3304:3306"
    environment:
      MYSQL_ROOT_PASSWORD: granada290378
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql-usuarios:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    #Construccion de la imagen
    #    build:
    #      context: ./
    #      dockerfile: ./msvc-usuarios/Dockerfile
    image: gonzalo290378/usuarios
    ports:
      - "8001:8001"
    #    ENVIRONMENT LOCAL
    #    env_file: ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql-usuarios:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: granada290378
      CURSOS_URL: ec2-54-198-134-113.compute-1.amazonaws.com:8002
    networks:
      - spring
    depends_on:
      - mysql-usuarios
    restart: always


#CONFIGURACION DE LOS VOLUMES PARA CADA BASE CON EL FIN DE SER SER UTILIZADA EN SERVICES
volumes:
  data-mysql-usuarios:
    name: data-mysql-usuarios

#CONFIGURACION DE LA NETWORD SPRING CON EL FIN SER UTILIZADA EN SERVICES
networks:
  spring:
    name: spring
    external: true