apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-gateway
  template:
    metadata:
      labels:
        role: msvc-gateway
    spec:
      containers:
        - name: msvc-gateway
          image: gonzalo290378/gateway:latest
          ports:
            - containerPort: 8090
---

apiVersion: v1
kind: Service
metadata:
  name: msvc-gateway
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  selector:
    role: msvc-gateway

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io